// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKrUTk7QrNSV3MMIu6k533ECn8zGqAiWI',
    appId: '1:976832560469:web:539ac939d3c755d76783dc',
    messagingSenderId: '976832560469',
    projectId: 'medisync-738eb',
    authDomain: 'medisync-738eb.firebaseapp.com',
    storageBucket: 'medisync-738eb.firebasestorage.app',
    measurementId: 'G-Z0K9E5TJVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKxEPlyTV6J37_9OIWA6Bm5pkzNFoUShQ',
    appId: '1:976832560469:android:ec3ac17c823bedad6783dc',
    messagingSenderId: '976832560469',
    projectId: 'medisync-738eb',
    storageBucket: 'medisync-738eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtz_sHbNVCjn7cTAhp21y5CFov5BxM7Oo',
    appId: '1:976832560469:ios:86d4cde5a2b5f5bb6783dc',
    messagingSenderId: '976832560469',
    projectId: 'medisync-738eb',
    storageBucket: 'medisync-738eb.firebasestorage.app',
    androidClientId: '976832560469-ug5u5m561vf4lqtec63t6qt8enf6v118.apps.googleusercontent.com',
    iosClientId: '976832560469-dlut35hs2hr0029bih2g7vta6qdv4jq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.medisyncDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtz_sHbNVCjn7cTAhp21y5CFov5BxM7Oo',
    appId: '1:976832560469:ios:86d4cde5a2b5f5bb6783dc',
    messagingSenderId: '976832560469',
    projectId: 'medisync-738eb',
    storageBucket: 'medisync-738eb.firebasestorage.app',
    androidClientId: '976832560469-ug5u5m561vf4lqtec63t6qt8enf6v118.apps.googleusercontent.com',
    iosClientId: '976832560469-dlut35hs2hr0029bih2g7vta6qdv4jq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.medisyncDoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKrUTk7QrNSV3MMIu6k533ECn8zGqAiWI',
    appId: '1:976832560469:web:0813bd91450fa4f96783dc',
    messagingSenderId: '976832560469',
    projectId: 'medisync-738eb',
    authDomain: 'medisync-738eb.firebaseapp.com',
    storageBucket: 'medisync-738eb.firebasestorage.app',
    measurementId: 'G-1V3V1ZBPH9',
  );
}
